{
    "name": "rtxzy",
    "version": "7.0.1",
    "description": "Lightweight WhatsApp Bot",
    "depecrated": false,
    "main": "index.js",
    "directories": {
        "lib": "lib",
        "src": "src",
        "plugins": "plugins"
    },
    "scripts": {
        "start": "node index.js --autocleartmp --autoread",
        "test": "node test.js",
        "test2": "nodemon index.js --server --autocleartmp --autoread"
    },
    "keywords": [
        "whatsapp-bot-md",
        "whatsapp-bot",
        "whatsapp",
        "js-whatsapp",
        "whatsapp",
        "Games-wabot",
        "wabot-aq",
        "whiskeysockets",
        "botcahx",
        "baileys"
    ],
    "homepage": "https://github.com/BOTCAHX/RTXZY-MD",
    "author": {
        "name": "BOTCAHX"
    },
    "repository": {
        "type": "git",
        "url": "git+https://github.com/BOTCAHX/RTXZY-MD.git"
    },
    "bugs": {
        "url": "https://github.com/BOTCAHX/RTXZY-MD/issues"
    },
    "license": "MIT",
    "dependencies": {
        "@adiwajshing/baileys": "npm:@whiskeysockets/baileys",
        "@adiwajshing/keyed-db": "^0.2.4",
        "@bochilteam/scraper": "^3.0.0",
        "@brandond/findthelyrics": "^2.0.5",
        "@vitalets/google-translate-api": "^9.0.0",
        "acrcloud": "^1.4.0",
        "javascript-obfuscator": "^4.0.2",
        "async": "^3.2.4",
        "aki-api": "^6.0.9",
        "awesome-phonenumber": "^2.64.0",
        "axios": "^0.27.2",
        "base64-to-image": "^1.0.2",
        "btch-downloader": "*",
        "chalk": "^4.1.2",
        "caliph-api": "^1.0.0",
        "didyoumean": "^1.2.2",
        "cheerio": "^1.0.0-rc.12",
        "colors": "1.4.0",
        "express": "^4.18.2",
        "file-type": "^16.5.3",
        "form-data": "^4.0.0",
        "formdata-node": "^6.0.3",
        "google-it": "^1.6.3",
        "human-readable": "^0.2.1",
        "hxz-api": "^1.0.1",
        "jsdom": "^20.0.0",
        "lodash": "^4.17.21",
        "lowdb": "^2.1.0",
        "link-preview-js": "^3.0.4",
        "moment-timezone": "^0.5.37",
        "mongoose": "^6.0.14",
        "mime-types": "^2.1.35",
        "node-fetch": "^2.7.0",
        "node-gtts": "2.0.2",
        "node-id3": "^0.2.6",
        "node-os-utils": "^1.3.7",
        "node-webpmux": "^3.1.3",
        "nodemon": "^2.0.20",
        "ocr-space-api-wrapper": "^2.2.0",
        "os": "^0.1.2",
        "perf_hooks": "^0.0.1",
        "qrcode": "^1.5.0",
        "qrcode-terminal": "^0.12.0",
        "readline": "^1.3.0",
        "similarity": "^1.2.1",
        "sharp": "^0.32.6",
        "spotifydl-core": "^0.2.0",
        "socket.io": "^4.5.1",
        "syntax-error": "^1.4.0",
        "terminal-image": "^2.0.0",
        "url": "^0.11.0",
        "url-regex": "^5.0.0",
        "url-regex-safe": "^2.1.0",
        "util": "^0.12.4",
        "wa-sticker-formatter": "^4.3.2",
        "xfarr-api": "^1.0.3",
        "yargs": "^17.5.1",
        "ytdl-core": "^4.11.5",
        "yt-search": "^2.10.3"
    }
}
